version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Europe/Zurich' # Set timezone
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '3306:3306'
    volumes:
      - ./lib:/var/lib/mysql
      - ./mysql-conf.d:/etc/mysql/conf.d
      - ./scripts/01-grant-permissions.sh:/docker-entrypoint-initdb.d/01-grant-permissions.sh
  dump:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dump
    volumes:
      - ./backup:/backup
      - ./scripts:/scripts
    depends_on:
      - mariadb
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Europe/Zurich' # Set timezone
